dependencies:
# - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: development
  development:
    # from here: https://docs.chain.link/docs/vrf-contracts/#rinkeby-testnet
    keyhash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    fee: 100000000000000000 #LINK in wei
    verify: False
  rinkeby: 
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    # vrf_coordinator here https://docs.chain.link/docs/vrf-contracts/#rinkeby-testnet
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    fee: 100000000000000000 #LINK in wei
    verify: True
  mainnet-fork: 
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419" #from ETH mainnet
  mainnet-fork-dev: 
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419" #from ETH mainnet
    verify: False  
  ganache-fundme:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}    
  